import {
  Clapperboard,
  Cuboid,
  Film,
  Image,
  Palette,
  MonitorSmartphone,
  Sparkles,
} from "lucide-react";

export const categories = [
  { name: "All", icon: Clapperboard },
  { name: "Video Edits", icon: Film },
  { name: "Motion Graphics", icon: Sparkles },
  { name: "3D", icon: Cuboid },
  { name: "VFX", icon: Sparkles },
  { name: "Photo Manipulation", icon: Image },
];

export const projects = [
  {
    id: 1,
    category: "3D",
    image: "/assets/Projects/image1.jpg",
    year: "2026",
    featured: true,
    type: "image",
    // videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 2,
    category: "Photo Manipulation",
    image: "/assets/Projects/y2kweeknd.png",
    year: "2026",
    featured: false,
    type: "image",
  },
  {
    id: 3,
    category: "3D",
    image: "/assets/Projects/image2.jpg",
    year: "2025",
    featured: false,
    type: "image",
    // videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 4,
    category: "3D",
    image: "/assets/Projects/image3.jpg",
    year: "2025",
    featured: false,
    type: "image",
    addon: {
      available: true,
      assetId: "b1",
    },
    // videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 7,
    category: "Photo Manipulation",
    image: "/assets/Projects/image6.png",
    year: "2024",
    featured: false,
    type: "image",
    // videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 8,
    category: "VFX",
    image: "/assets/Projects/image7.jpeg",
    year: "2024",
    featured: false,
    type: "video",
    videoUrl: "https://youtu.be/XqMJu_VdJM4?si=KC1BQ66x3npG7Fla",
  },
  {
    id: 9,
    category: "VFX",
    image: "/assets/Projects/image8.jpeg",
    year: "2024",
    featured: false,
    type: "video",
    videoUrl: "https://youtu.be/8C0op1dXdec?is=pUpbfu_SGwXJlQ7M",
  },
  {
    id: 10,
    category: "VFX",
    image: "/assets/Projects/image9.jpeg",
    year: "2024",
    featured: false,
    type: "video",
    videoUrl: "https://youtu.be/MVvjsDDOjpw?is=ZS-C0mnXEzwYOzG3",
  },
  {
    id: 11,
    category: "Video Edits",
    image: "/assets/Projects/image10.jpeg",
    year: "2024",
    featured: false,
    type: "video",
    videoUrl: "https://youtu.be/fSWKJpSQKjE",
  },
  {
    id: 12,
    category: "3D",
    image: "/assets/Projects/image11.jpeg",
    year: "2024",
    featured: false,
    type: "image",
    videoUrl: "",
  },
  {
    id: 14,
    category: "3D",
    image: "/assets/Projects/image13.jpg",
    year: "2025",
    featured: false,
    type: "image",
    // videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: 16,
    category: "3D",
    image: "/assets/Projects/image15.jpg",
     year: "2026",
    featured: false,
    type: "video",
    videoUrl: "https://youtu.be/M4fPpJ7GrEA",
  },
   {
    id: 17,
    category: "3D",
    image: "/assets/Projects/image16.png",
     year: "2026",
    featured: false,
    type: "image",
    // videoUrl: "https://youtu.be/M4fPpJ7GrEA",
  },
  {
    id: 18,
    category: "Photo Manipulation",
    image: "/assets/Projects/image17.jpg",
     year: "2026",
    featured: false,
    type: "image",
    // videoUrl: "https://youtu.be/M4fPpJ7GrEA",
  },
  {
    id: 19,
    category: "3D",
    image: "/assets/Projects/cyberpunk-bkd.jpg",
    year: "2026",
    featured: false,
    type: "image",
  },
  {
    id: 20,
    category: "Photo Manipulation",
    image: "/assets/Projects/photo_2026-08-22_07-23-02.jpg",
    year: "2026",
    featured: false,
    type: "image",
  },
  {
    id: 21,
    category: "Photo Manipulation",
    image: "/assets/Projects/photo_2026-08-22_07-23-04.jpg",
    year: "2026",
    featured: false,
    type: "image",
  },
  {
    id: 22,
    category: "Photo Manipulation",
    image: "/assets/Projects/photo_2026-08-22_07-23-06.jpg",
    year: "2026",
    featured: false,
    type: "image",
  },
];

export const assetData = [
  // Blender assets
  {
    id: "b1",
    name: "Cyber city",
    extension: ".blend",
    software: "Blender",
    year: "2026",
    downloadLink: "https://t.me/triplevisionaryarchive/13",
  },
];

export const softwareList = [
  "All",
  "Blender",
  "After Effects",
  "Premiere Pro",
  "Fusion",
  "Photoshop",
  "GIMP",
  "Inkscape",
  "Illustrator",
  "Natron",
  "Kdenlive",
  ".fbx",
  ".obj",
  ".png",
  ".exr",
  ".jpeg",
  ".tiff",
];
